# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='msg.proto',
  package='',
  serialized_pb='\n\tmsg.proto\"\xf5\x03\n\tBudgetMsg\x12\x1f\n\nbudgettype\x18\x01 \x01(\x0e\x32\x0b.BudgetType\x12\x0e\n\x06userid\x18\x02 \x01(\x04\x12\x0e\n\x06planid\x18\x03 \x01(\r\x12\x13\n\x0buserbalance\x18\x04 \x01(\x02\x12\x12\n\nuserbudget\x18\x05 \x01(\x02\x12\x10\n\x08usercost\x18\x06 \x01(\x02\x12\x12\n\nplanbudget\x18\x07 \x01(\x02\x12\x10\n\x08plancost\x18\x08 \x01(\x02\x12\r\n\x05query\x18\t \x01(\x0c\x12\x0b\n\x03src\x18\n \x01(\x0c\x12\x0f\n\x07keyword\x18\x0b \x01(\x0c\x12\x12\n\nclickprice\x18\x0c \x01(\x02\x12\x1b\n\tmatchtype\x18\r \x01(\x0e\x32\x08.BidType\x12\x12\n\nchargetime\x18\x0e \x01(\x04\x12\x0c\n\x04lsid\x18\x0f \x01(\x04\x12\x11\n\tclicktime\x18\x10 \x01(\r\x12\x10\n\x08\x64\x65\x61ltime\x18\x11 \x01(\r\x12\x10\n\x08gspprice\x18\x12 \x01(\x02\x12\x11\n\tbucket_id\x18\x13 \x01(\r\x12\x10\n\x08\x62idprice\x18\x14 \x01(\x02\x12\x1c\n\x14is_balce_show_update\x18\x15 \x01(\x08\x12\x1a\n\x12is_bgt_show_update\x18\x16 \x01(\x08\x12\x1b\n\x13is_plan_show_update\x18\x17 \x01(\x08\x12\x13\n\x0bis_unfreeze\x18\x18 \x01(\x08\"q\n\x0e\x41\x64\x42udgetMsgReq\x12\r\n\x05msgid\x18\x01 \x01(\x04\x12\x10\n\x08msg_time\x18\x02 \x01(\r\x12\x1f\n\x07msgtype\x18\x03 \x01(\x0e\x32\x0e.BudgetMsgType\x12\x1d\n\tbudgetmsg\x18\x04 \x01(\x0b\x32\n.BudgetMsg*+\n\x07\x42idType\x12\t\n\x05\x45XACT\x10\x01\x12\n\n\x06PHRASE\x10\x02\x12\t\n\x05\x42ROAD\x10\x03*w\n\nBudgetType\x12\x0b\n\x07\x43ONSUME\x10\x01\x12\x0c\n\x08RECHARGE\x10\x02\x12\x11\n\rMODIFY_BUDGET\x10\x03\x12\r\n\tANTI_SPAM\x10\x04\x12\x08\n\x04\x43OST\x10\x05\x12\x0b\n\x07\x42\x41LANCE\x10\x06\x12\x15\n\x11SHOW_COUNT_UPDATE\x10\x07*0\n\rBudgetMsgType\x12\x0f\n\x0b\x42UDGET_DATA\x10\x01\x12\x0e\n\nREQ_UPDATE\x10\x02')

_BIDTYPE = descriptor.EnumDescriptor(
  name='BidType',
  full_name='BidType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='EXACT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PHRASE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BROAD', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=632,
  serialized_end=675,
)


_BUDGETTYPE = descriptor.EnumDescriptor(
  name='BudgetType',
  full_name='BudgetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CONSUME', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RECHARGE', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='MODIFY_BUDGET', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ANTI_SPAM', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='COST', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BALANCE', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SHOW_COUNT_UPDATE', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=677,
  serialized_end=796,
)


_BUDGETMSGTYPE = descriptor.EnumDescriptor(
  name='BudgetMsgType',
  full_name='BudgetMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='BUDGET_DATA', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REQ_UPDATE', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=798,
  serialized_end=846,
)


EXACT = 1
PHRASE = 2
BROAD = 3
CONSUME = 1
RECHARGE = 2
MODIFY_BUDGET = 3
ANTI_SPAM = 4
COST = 5
BALANCE = 6
SHOW_COUNT_UPDATE = 7
BUDGET_DATA = 1
REQ_UPDATE = 2



_BUDGETMSG = descriptor.Descriptor(
  name='BudgetMsg',
  full_name='BudgetMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='budgettype', full_name='BudgetMsg.budgettype', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userid', full_name='BudgetMsg.userid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='planid', full_name='BudgetMsg.planid', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userbalance', full_name='BudgetMsg.userbalance', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='userbudget', full_name='BudgetMsg.userbudget', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='usercost', full_name='BudgetMsg.usercost', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='planbudget', full_name='BudgetMsg.planbudget', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='plancost', full_name='BudgetMsg.plancost', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='query', full_name='BudgetMsg.query', index=8,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='src', full_name='BudgetMsg.src', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='keyword', full_name='BudgetMsg.keyword', index=10,
      number=11, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clickprice', full_name='BudgetMsg.clickprice', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='matchtype', full_name='BudgetMsg.matchtype', index=12,
      number=13, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='chargetime', full_name='BudgetMsg.chargetime', index=13,
      number=14, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lsid', full_name='BudgetMsg.lsid', index=14,
      number=15, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='clicktime', full_name='BudgetMsg.clicktime', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dealtime', full_name='BudgetMsg.dealtime', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='gspprice', full_name='BudgetMsg.gspprice', index=17,
      number=18, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bucket_id', full_name='BudgetMsg.bucket_id', index=18,
      number=19, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bidprice', full_name='BudgetMsg.bidprice', index=19,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_balce_show_update', full_name='BudgetMsg.is_balce_show_update', index=20,
      number=21, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_bgt_show_update', full_name='BudgetMsg.is_bgt_show_update', index=21,
      number=22, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_plan_show_update', full_name='BudgetMsg.is_plan_show_update', index=22,
      number=23, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='is_unfreeze', full_name='BudgetMsg.is_unfreeze', index=23,
      number=24, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=14,
  serialized_end=515,
)


_ADBUDGETMSGREQ = descriptor.Descriptor(
  name='AdBudgetMsgReq',
  full_name='AdBudgetMsgReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='msgid', full_name='AdBudgetMsgReq.msgid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msg_time', full_name='AdBudgetMsgReq.msg_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='msgtype', full_name='AdBudgetMsgReq.msgtype', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='budgetmsg', full_name='AdBudgetMsgReq.budgetmsg', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=517,
  serialized_end=630,
)

_BUDGETMSG.fields_by_name['budgettype'].enum_type = _BUDGETTYPE
_BUDGETMSG.fields_by_name['matchtype'].enum_type = _BIDTYPE
_ADBUDGETMSGREQ.fields_by_name['msgtype'].enum_type = _BUDGETMSGTYPE
_ADBUDGETMSGREQ.fields_by_name['budgetmsg'].message_type = _BUDGETMSG
DESCRIPTOR.message_types_by_name['BudgetMsg'] = _BUDGETMSG
DESCRIPTOR.message_types_by_name['AdBudgetMsgReq'] = _ADBUDGETMSGREQ

class BudgetMsg(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BUDGETMSG
  
  # @@protoc_insertion_point(class_scope:BudgetMsg)

class AdBudgetMsgReq(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ADBUDGETMSGREQ
  
  # @@protoc_insertion_point(class_scope:AdBudgetMsgReq)

# @@protoc_insertion_point(module_scope)
